Student.create(name: "Kelsey Shiba", email: "kelseyshiba@kelseyshiba.com", password: "kelseyshiba", phone: "303727484")
Student.create(name: "Whitney Shiba", email: "whitneyshiba@whitneyshiba.com", password: "whitneyshiba", phone: "303727485")
Student.create(name: "Pam Shiba", email: "pamshiba@pamshiba.com", password: "pamshiba", phone: "303727486")
Student.create(name: "Bob Shiba", email: "bobshiba@bobshiba.com", password: "bobshiba", phone: "303727487")
Student.create(name: "Jordan Shiba", email: "jordanshiba@jordanshiba.com", password: "jordanshiba", phone: "303727488")
Student.create(name: "Nance White", email: "nancewhite@nancewhite.com", password: "nancewhite", phone: "3037277489")
Student.create(name: "Larry White", email: "larrywhite@larrywhite.com", password: "larrywhite", phone: "3037277490")
Student.create(name: "Lauren Henry", email: "laurenhenry@laurenhenry.com", password: "laurenhenrty", phone: "3037277491")

Teacher.create(name: "Jim White", email: "jimwhite@jimwhite.com", password: "jimwhite" )
Teacher.create(name: "Erik Applegate", email: "erikapplegate@erikapplegate.com", password: "erikapplegate" )
Teacher.create(name: "Dana Landry", email: "danalandry@danalandry.com", password: "danalandry" )
Teacher.create(name: "Steve Kovalcheck", email: "stevekovalcheck@stevekovalcheck.com", password: "stevekovalcheck" )
Teacher.create(name: "Brian Casey", email: "briancasey@briancasey.com", password: "briancasey" )